"""
This file is automatically generated.
Do not modify.
"""

try:
    from typing import Any, Optional, Union, List
except ImportError:
    pass

from ._helper import _omit, CrdObject, CrdObjectList

class Gateway(CrdObject):
    _properties = [
        ('type', 'type', str, False, False),
        ('sslCertificateRef', 'sslCertificateRef', object, False, False),
        ('port', 'port', int, False, False),
        ('securePort', 'securePort', object, False, False),
        ('instances', 'instances', int, False, False),
        ('annotations', 'annotations', object, False, False),
        ('placement', 'placement', object, False, False),
        ('resources', 'resources', object, False, False)
    ]        

    def __init__(self,
                 type=_omit,  # type: Optional[str]
                 sslCertificateRef=_omit,  # type: Optional[Any]
                 port=_omit,  # type: Optional[int]
                 securePort=_omit,  # type: Optional[Any]
                 instances=_omit,  # type: Optional[int]
                 annotations=_omit,  # type: Optional[Any]
                 placement=_omit,  # type: Optional[Any]
                 resources=_omit,  # type: Optional[Any]
                 ):
        self.type = type  # type: ignore
        self.sslCertificateRef = sslCertificateRef  # type: ignore
        self.port = port  # type: ignore
        self.securePort = securePort  # type: ignore
        self.instances = instances  # type: ignore
        self.annotations = annotations  # type: ignore
        self.placement = placement  # type: ignore
        self.resources = resources  # type: ignore

    @property
    def type(self):
        # type: () -> str
        return self._property_impl('type')
    
    @type.setter
    def type(self, new_val):
        # type: (Optional[str]) -> None
        self._type = new_val
    
    @property
    def sslCertificateRef(self):
        # type: () -> Any
        return self._property_impl('sslCertificateRef')
    
    @sslCertificateRef.setter
    def sslCertificateRef(self, new_val):
        # type: (Optional[Any]) -> None
        self._sslCertificateRef = new_val
    
    @property
    def port(self):
        # type: () -> int
        return self._property_impl('port')
    
    @port.setter
    def port(self, new_val):
        # type: (Optional[int]) -> None
        self._port = new_val
    
    @property
    def securePort(self):
        # type: () -> Any
        return self._property_impl('securePort')
    
    @securePort.setter
    def securePort(self, new_val):
        # type: (Optional[Any]) -> None
        self._securePort = new_val
    
    @property
    def instances(self):
        # type: () -> int
        return self._property_impl('instances')
    
    @instances.setter
    def instances(self, new_val):
        # type: (Optional[int]) -> None
        self._instances = new_val
    
    @property
    def annotations(self):
        # type: () -> Any
        return self._property_impl('annotations')
    
    @annotations.setter
    def annotations(self, new_val):
        # type: (Optional[Any]) -> None
        self._annotations = new_val
    
    @property
    def placement(self):
        # type: () -> Any
        return self._property_impl('placement')
    
    @placement.setter
    def placement(self, new_val):
        # type: (Optional[Any]) -> None
        self._placement = new_val
    
    @property
    def resources(self):
        # type: () -> Any
        return self._property_impl('resources')
    
    @resources.setter
    def resources(self, new_val):
        # type: (Optional[Any]) -> None
        self._resources = new_val


class Replicated(CrdObject):
    _properties = [
        ('size', 'size', int, False, False)
    ]        

    def __init__(self,
                 size=_omit,  # type: Optional[int]
                 ):
        self.size = size  # type: ignore

    @property
    def size(self):
        # type: () -> int
        return self._property_impl('size')
    
    @size.setter
    def size(self, new_val):
        # type: (Optional[int]) -> None
        self._size = new_val


class ErasureCoded(CrdObject):
    _properties = [
        ('dataChunks', 'dataChunks', int, False, False),
        ('codingChunks', 'codingChunks', int, False, False)
    ]        

    def __init__(self,
                 dataChunks=_omit,  # type: Optional[int]
                 codingChunks=_omit,  # type: Optional[int]
                 ):
        self.dataChunks = dataChunks  # type: ignore
        self.codingChunks = codingChunks  # type: ignore

    @property
    def dataChunks(self):
        # type: () -> int
        return self._property_impl('dataChunks')
    
    @dataChunks.setter
    def dataChunks(self, new_val):
        # type: (Optional[int]) -> None
        self._dataChunks = new_val
    
    @property
    def codingChunks(self):
        # type: () -> int
        return self._property_impl('codingChunks')
    
    @codingChunks.setter
    def codingChunks(self, new_val):
        # type: (Optional[int]) -> None
        self._codingChunks = new_val


class MetadataPool(CrdObject):
    _properties = [
        ('failureDomain', 'failureDomain', str, False, False),
        ('replicated', 'replicated', Replicated, False, False),
        ('erasureCoded', 'erasureCoded', ErasureCoded, False, False)
    ]        

    def __init__(self,
                 failureDomain=_omit,  # type: Optional[str]
                 replicated=_omit,  # type: Optional[Replicated]
                 erasureCoded=_omit,  # type: Optional[ErasureCoded]
                 ):
        self.failureDomain = failureDomain  # type: ignore
        self.replicated = replicated  # type: ignore
        self.erasureCoded = erasureCoded  # type: ignore

    @property
    def failureDomain(self):
        # type: () -> str
        return self._property_impl('failureDomain')
    
    @failureDomain.setter
    def failureDomain(self, new_val):
        # type: (Optional[str]) -> None
        self._failureDomain = new_val
    
    @property
    def replicated(self):
        # type: () -> Replicated
        return self._property_impl('replicated')
    
    @replicated.setter
    def replicated(self, new_val):
        # type: (Optional[Replicated]) -> None
        self._replicated = new_val
    
    @property
    def erasureCoded(self):
        # type: () -> ErasureCoded
        return self._property_impl('erasureCoded')
    
    @erasureCoded.setter
    def erasureCoded(self, new_val):
        # type: (Optional[ErasureCoded]) -> None
        self._erasureCoded = new_val


class DataPool(CrdObject):
    _properties = [
        ('failureDomain', 'failureDomain', str, False, False),
        ('replicated', 'replicated', Replicated, False, False),
        ('erasureCoded', 'erasureCoded', ErasureCoded, False, False)
    ]        

    def __init__(self,
                 failureDomain=_omit,  # type: Optional[str]
                 replicated=_omit,  # type: Optional[Replicated]
                 erasureCoded=_omit,  # type: Optional[ErasureCoded]
                 ):
        self.failureDomain = failureDomain  # type: ignore
        self.replicated = replicated  # type: ignore
        self.erasureCoded = erasureCoded  # type: ignore

    @property
    def failureDomain(self):
        # type: () -> str
        return self._property_impl('failureDomain')
    
    @failureDomain.setter
    def failureDomain(self, new_val):
        # type: (Optional[str]) -> None
        self._failureDomain = new_val
    
    @property
    def replicated(self):
        # type: () -> Replicated
        return self._property_impl('replicated')
    
    @replicated.setter
    def replicated(self, new_val):
        # type: (Optional[Replicated]) -> None
        self._replicated = new_val
    
    @property
    def erasureCoded(self):
        # type: () -> ErasureCoded
        return self._property_impl('erasureCoded')
    
    @erasureCoded.setter
    def erasureCoded(self, new_val):
        # type: (Optional[ErasureCoded]) -> None
        self._erasureCoded = new_val


class Spec(CrdObject):
    _properties = [
        ('gateway', 'gateway', Gateway, False, False),
        ('metadataPool', 'metadataPool', MetadataPool, False, False),
        ('dataPool', 'dataPool', DataPool, False, False)
    ]        

    def __init__(self,
                 gateway=_omit,  # type: Optional[Gateway]
                 metadataPool=_omit,  # type: Optional[MetadataPool]
                 dataPool=_omit,  # type: Optional[DataPool]
                 ):
        self.gateway = gateway  # type: ignore
        self.metadataPool = metadataPool  # type: ignore
        self.dataPool = dataPool  # type: ignore

    @property
    def gateway(self):
        # type: () -> Gateway
        return self._property_impl('gateway')
    
    @gateway.setter
    def gateway(self, new_val):
        # type: (Optional[Gateway]) -> None
        self._gateway = new_val
    
    @property
    def metadataPool(self):
        # type: () -> MetadataPool
        return self._property_impl('metadataPool')
    
    @metadataPool.setter
    def metadataPool(self, new_val):
        # type: (Optional[MetadataPool]) -> None
        self._metadataPool = new_val
    
    @property
    def dataPool(self):
        # type: () -> DataPool
        return self._property_impl('dataPool')
    
    @dataPool.setter
    def dataPool(self, new_val):
        # type: (Optional[DataPool]) -> None
        self._dataPool = new_val


class CephObjectStore(CrdObject):
    _properties = [
        ('apiVersion', 'apiVersion', str, True, False),
        ('kind', 'kind', str, True, False),
        ('metadata', 'metadata', object, True, False),
        ('status', 'status', object, False, False),
        ('spec', 'spec', Spec, True, False)
    ]        

    def __init__(self,
                 apiVersion,  # type: str
                 metadata,  # type: Any
                 spec,  # type: Spec
                 kind="CephObjectStore",  # type: str
                 status=_omit,  # type: Optional[Any]
                 ):
        self.apiVersion = apiVersion  # type: ignore
        self.metadata = metadata  # type: ignore
        self.spec = spec  # type: ignore
        self.kind = kind  # type: ignore
        self.status = status  # type: ignore

    @property
    def apiVersion(self):
        # type: () -> str
        return self._property_impl('apiVersion')
    
    @apiVersion.setter
    def apiVersion(self, new_val):
        # type: (str) -> None
        self._apiVersion = new_val
    
    @property
    def kind(self):
        # type: () -> str
        return self._property_impl('kind')
    
    @kind.setter
    def kind(self, new_val):
        # type: (str) -> None
        self._kind = new_val
    
    @property
    def metadata(self):
        # type: () -> Any
        return self._property_impl('metadata')
    
    @metadata.setter
    def metadata(self, new_val):
        # type: (Any) -> None
        self._metadata = new_val
    
    @property
    def status(self):
        # type: () -> Any
        return self._property_impl('status')
    
    @status.setter
    def status(self, new_val):
        # type: (Optional[Any]) -> None
        self._status = new_val
    
    @property
    def spec(self):
        # type: () -> Spec
        return self._property_impl('spec')
    
    @spec.setter
    def spec(self, new_val):
        # type: (Spec) -> None
        self._spec = new_val
