name: Python application

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        py_version: [2.7, 3.5, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.py_version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.py_version }}
    - name: clone rook
      run: |
        git clone --depth 1 https://github.com/rook/rook.git
    - name: Run generate.sh
      run: |
        ./generate.sh $PWD/rook
